### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jiyewushen** [KunMinX/Jetpack-MVVM-Scaffold#3]
```java
06-12 19:53:28.908 17155-17155/com.kunminx.scaffold E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kunminx.scaffold, PID: 17155
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory;
        at com.danikula.videocache.StorageUtils.<clinit>(StorageUtils.java:23)
        at com.danikula.videocache.HttpProxyCacheServer$Builder.<init>(HttpProxyCacheServer.java:359)
        at com.kunminx.puremusic.player.PlayerManager.init(PlayerManager.java:67)
        at com.kunminx.puremusic.player.PlayerManager.init(PlayerManager.java:60)
        at com.kunminx.puremusic.App.onCreate(App.java:42)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5014)
        at android.app.ActivityThread.access$1600(ActivityThread.java:169)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:5751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.slf4j.LoggerFactory" on path: DexPathList[[zip file "/data/app/com.kunminx.scaffold-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kunminx.scaffold-1/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.danikula.videocache.StorageUtils.<clinit>(StorageUtils.java:23) 
        at com.danikula.videocache.HttpProxyCacheServer$Builder.<init>(HttpProxyCacheServer.java:359) 
        at com.kunminx.puremusic.player.PlayerManager.init(PlayerManager.java:67) 
        at com.kunminx.puremusic.player.PlayerManager.init(PlayerManager.java:60) 
        at com.kunminx.puremusic.App.onCreate(App.java:42) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5014) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:169) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:5751) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622) 
    	Suppressed: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 16 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by KunMinX** [comment]
已修复
